apiVersion: v1
kind: Service
metadata:
  name: jira
spec:
  type: LoadBalancer
  selector:
    {{- include "jira.selectorLabels" . | nindent 8 }}
  ports:
    - protocol  : TCP
      port      : 80
      targetPort: 8080